version: "3.7"

services:
  api:
    build: api/
    container_name: api
    restart: always
    depends_on:
      - db
    links:
      - db
    ports:
      - 8080:8080
    environment:
      - APPLICATION_NAME=API
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - VPNROUTER_LOG_PATH=${VPNROUTER_LOG_PATH}
      - VPNROUTER_LOG_ARCHIVE_PATH=${VPNROUTER_LOG_ARCHIVE_PATH}
    volumes:
      - /home/vpnrouter/logs:/logs

  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - /home/vpnrouter/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432